name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (client)
        run: npm install --prefix client

      - name: Install dependencies (server)
        run: npm install --prefix server

      - name: Build project (client)
        run: npm run build --prefix client

      - name: Build project (server)
        run: npm run start --prefix server

      - name: Upload client production files
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist

      - name: Upload server production files
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: server/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download client artifact
        uses: actions/download-artifact@v4
        with:
          name: client-dist
          path: ./dist/client

      - name: Download server artifact
        uses: actions/download-artifact@v4
        with:
          name: server-dist
          path: ./dist/server

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/client
